/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MindmapPreviewRouteImport } from './routes/mindmap-preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkbenchRouteImport } from './routes/_authenticated/workbench'

const MindmapPreviewRoute = MindmapPreviewRouteImport.update({
  id: '/mindmap-preview',
  path: '/mindmap-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkbenchRoute = AuthenticatedWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mindmap-preview': typeof MindmapPreviewRoute
  '/workbench': typeof AuthenticatedWorkbenchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mindmap-preview': typeof MindmapPreviewRoute
  '/workbench': typeof AuthenticatedWorkbenchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mindmap-preview': typeof MindmapPreviewRoute
  '/_authenticated/workbench': typeof AuthenticatedWorkbenchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/mindmap-preview' | '/workbench'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/mindmap-preview' | '/workbench'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mindmap-preview'
    | '/_authenticated/workbench'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MindmapPreviewRoute: typeof MindmapPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mindmap-preview': {
      id: '/mindmap-preview'
      path: '/mindmap-preview'
      fullPath: '/mindmap-preview'
      preLoaderRoute: typeof MindmapPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workbench': {
      id: '/_authenticated/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof AuthenticatedWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkbenchRoute: typeof AuthenticatedWorkbenchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkbenchRoute: AuthenticatedWorkbenchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MindmapPreviewRoute: MindmapPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
